version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    command: bin/rails s -p 3000 -b '0.0.0.0'
    environment:
      APP_DATABASE_USERNAME: root
      APP_DATABASE_PASSWORD: password
      APP_DATABASE_HOST: db
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
